# Site settings 配置站点
title: 'KYO'
description: 'KYO'
keywords: 'php laravel js mysql bootstrap vue.js weixin linux'
url: 'https://kyoapps-kyo.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  KYO: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'kyo'
NickName: 'kyo'
webtitle: 'Stay hungry, stay foolish.'
bio: ''
about: true
aboutyou: '保持好奇，不断积累'
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:kyo@kyoapps.com'
  weixin: '/assets/wxqrcode-kyotowy.jpeg' # 你的微信二维码存放的地址
  # qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='2106208317'&site=qq&menu=yes
  github: 'https://github.com/kyoapps-kyo'
  # Codepen: ''
  weibo: 'https://weibo.com/7392086588/profile?topnav=1&wvr=6&is_all=1'
  instagram: ''
  # Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 10
paginatepath: ['page:num']

# since
footer:
  since: 2021

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'
  github: 'https://github.com/kyoapps-kyo'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC81NDUxMi8zMDk4Mw==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '00eaba5de0a36c661fd413a3f8f1b936'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: true
google-ID: 'G-CTJ8G9J19M'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
